/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import com.mysql.jdbc.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author ADMIN-PC
 */
public class kamar
        extends javax.swing.JPanel {

    /**
     * Creates new form kamar
     */
    public kamar() {
        initComponents();
        datatableKamar();
        Validasi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKamar = new javax.swing.JTable();
        lblTamu = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdKamar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtJenisKamar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTarifKamar = new javax.swing.JTextField();
        btnSaveKamar = new javax.swing.JButton();
        btnDelKamar = new javax.swing.JButton();
        btnCancelKamar = new javax.swing.JButton();
        btnUpdateKamar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelKamar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabelKamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelKamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKamarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelKamar);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 61, -1, 202));

        lblTamu.setBackground(new java.awt.Color(204, 0, 0));
        lblTamu.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblTamu.setForeground(new java.awt.Color(255, 255, 255));
        lblTamu.setText("                    KAMAR");
        lblTamu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTamu.setOpaque(true);
        add(lblTamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 11, 500, 32));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(210, 202));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("KODE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 15, 38, -1));

        txtIdKamar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdKamarKeyReleased(evt);
            }
        });
        jPanel1.add(txtIdKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 12, 78, -1));

        jLabel2.setText("JENIS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 53, 40, -1));
        jPanel1.add(txtJenisKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 50, 135, -1));

        jLabel3.setText("TARIF");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 91, 39, -1));
        jPanel1.add(txtTarifKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 88, 78, -1));

        btnSaveKamar.setText("Save");
        btnSaveKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveKamarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 126, 63, -1));

        btnDelKamar.setText("Delete");
        btnDelKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelKamarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 155, -1, -1));

        btnCancelKamar.setText("Cancel");
        btnCancelKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelKamarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 155, 67, -1));

        btnUpdateKamar.setText("Update");
        btnUpdateKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateKamarActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdateKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 126, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 61, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 750, 40));
    }// </editor-fold>//GEN-END:initComponents

    public void Validasi(){
        btnSaveKamar.setEnabled(false);
        btnUpdateKamar.setEnabled(false);
        btnDelKamar.setEnabled(false);
    }
    
    public void datatableKamar(){
    DefaultTableModel tbl=new DefaultTableModel();
        tbl.addColumn("ID");
        tbl.addColumn("Jenis");
        tbl.addColumn("Tarif");
        tabelKamar.setModel(tbl);
        tabelKamar.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabelKamar.getColumnModel().getColumn(0).setPreferredWidth(60);        
        tabelKamar.getColumnModel().getColumn(1).setPreferredWidth(200);
        tabelKamar.getColumnModel().getColumn(2).setPreferredWidth(80);                
        try{
            Statement statement= (Statement) koneksi.GetConnection() .createStatement();
            ResultSet res=statement.executeQuery("SELECT * FROM tb_kamar_826");
                        
            while (res.next())
                
            {
                tbl.addRow(new Object[]{
                    res.getString ("kode_kamar"),
                    res.getString ("jenis_kamar"),
                    res.getString ("tarif")
            });
                tabelKamar.setModel(tbl);
        }
    }catch (Exception e){
        JOptionPane.showMessageDialog(tabelKamar, "Data Kamar Tidak Ditemukan");
        }
    }
        
    private void btnSaveKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveKamarActionPerformed
        if(txtIdKamar.getText().equals("")){  
            JOptionPane.showMessageDialog(null,"ID Tidak Boleh Kosong"); 
            }else if(txtJenisKamar.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Jenis Tidak Boleh Kosong"); 
            }else if (txtTarifKamar.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Tarif Tidak Boleh Kosong"); 
            }else{
                String Id = txtIdKamar.getText();
                String Jenis = txtJenisKamar.getText();
                String Tarif = txtTarifKamar.getText();
                try {
                    Statement statement = (Statement) koneksi.GetConnection() .createStatement();
                    statement.executeUpdate("insert into tb_kamar_826 VALUES ('" + Id + "','"+ Jenis + "','" + Tarif +"');");
                    statement.close();

                    JOptionPane.showMessageDialog(null, "Data Petugas berhasil disimpan");
                }catch (Exception t){
                    JOptionPane.showMessageDialog(null, "Data Petugas gagal disimpan");
                }
                datatableKamar();
            }    
    }//GEN-LAST:event_btnSaveKamarActionPerformed

    private void btnUpdateKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateKamarActionPerformed
        String Id_Kamar  = txtIdKamar.getText();
        String Jenis     = txtJenisKamar.getText();
        String Tarif     = txtTarifKamar.getText();
        
        try {
            PreparedStatement ps=(PreparedStatement) koneksi.GetConnection() .prepareStatement("UPDATE tb_kamar_826 set " +
                    "jenis_kamar=?, tarif=? where kode_kamar=?");
            ps.setString(1, Jenis);
            ps.setString(2, Tarif);
            ps.setString(3, Id_Kamar);
            ps.executeUpdate();
            ps.close();
           JOptionPane.showMessageDialog(null, "Berhasil Diubah");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Diubah");
        }
        datatableKamar();   
    }//GEN-LAST:event_btnUpdateKamarActionPerformed

    private void tabelKamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKamarMouseClicked
        int kolom =0;
        int baris   = tabelKamar.getSelectedRow();
        String ID   = tabelKamar.getModel().getValueAt(baris, kolom).toString();
        String Jenis = tabelKamar.getModel().getValueAt(baris, 1).toString();
        String Tarif = tabelKamar.getModel().getValueAt(baris, 2).toString();
        
        txtIdKamar.setText(ID);
        txtJenisKamar.setText(Jenis);
        txtTarifKamar.setText(Tarif);
        
        btnUpdateKamar.setEnabled(true);
        btnDelKamar.setEnabled(true);
        btnSaveKamar.setEnabled(false);
    }//GEN-LAST:event_tabelKamarMouseClicked

    private void btnDelKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelKamarActionPerformed
        String Id_Kamar = txtIdKamar.getText();
        
        try {
            Statement statement = (Statement) koneksi.GetConnection() .createStatement();
            statement.executeUpdate("DELETE from tb_kamar_826 WHERE kode_kamar=('"+Id_Kamar+"');");
            JOptionPane.showMessageDialog(null, "Berhasil Di Hapus");
            
            txtIdKamar.setText("");
            txtJenisKamar.setText("");
            txtTarifKamar.setText("");
            
        } catch (Exception t) {
            JOptionPane.showMessageDialog(null, "Gagal DI Hapus");
        }
        datatableKamar();
        btnSaveKamar.setEnabled(true);
        btnUpdateKamar.setEnabled(true);
        btnDelKamar.setEnabled(false);
    }//GEN-LAST:event_btnDelKamarActionPerformed

    private void btnCancelKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelKamarActionPerformed
        txtIdKamar.setText("");
        txtJenisKamar.setText("");
        txtTarifKamar.setText("");
        
    }//GEN-LAST:event_btnCancelKamarActionPerformed

    private void txtIdKamarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKamarKeyReleased
        btnUpdateKamar.setEnabled(false);
        btnDelKamar.setEnabled(false);
        
        if(txtIdKamar.getText().equals("")){
        btnSaveKamar.setEnabled(false);        
        }else{
            btnSaveKamar.setEnabled(true);
            
        }
    }//GEN-LAST:event_txtIdKamarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelKamar;
    private javax.swing.JButton btnDelKamar;
    private javax.swing.JButton btnSaveKamar;
    private javax.swing.JButton btnUpdateKamar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTamu;
    private javax.swing.JTable tabelKamar;
    private javax.swing.JTextField txtIdKamar;
    private javax.swing.JTextField txtJenisKamar;
    private javax.swing.JTextField txtTarifKamar;
    // End of variables declaration//GEN-END:variables
}
