/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import com.mysql.jdbc.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author ADMIN-PC
 */
public class reg
        extends javax.swing.JPanel {

    /**
     * Creates new form reg
     */
    public reg() {
        initComponents();
        comKDkamar();
        comKDpenghuni();
        datatableReg();
        Validasi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTamu = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNoReg = new javax.swing.JTextField();
        txtLama = new javax.swing.JTextField();
        txtTanggal = new com.toedter.calendar.JDateChooser();
        txtTarif = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNamaPenghuni = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtJenis = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsKDkamar = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lsKDpenghuni = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelReg = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnSaveReg = new javax.swing.JButton();
        btnUpdateReg = new javax.swing.JButton();
        btnCancelReg = new javax.swing.JButton();
        btnDeleteReg = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLabel5 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(840, 460));
        setPreferredSize(new java.awt.Dimension(930, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTamu.setBackground(new java.awt.Color(204, 0, 0));
        lblTamu.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblTamu.setForeground(new java.awt.Color(255, 255, 255));
        lblTamu.setText("                    REGISTRASI");
        lblTamu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTamu.setOpaque(true);
        add(lblTamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 530, 32));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("ID PEGHUNI");

        jLabel6.setText("KODE KAMAR");

        jLabel4.setText("TARIF");

        jLabel3.setText("LAMA MENGINAP");

        jLabel2.setText("TANGGAL");

        jLabel1.setText("NO REG.");

        txtNoReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNoRegKeyReleased(evt);
            }
        });

        txtLama.setText("1");

        jLabel8.setText("NAMA PENGHUNI");

        jLabel9.setText("JENIS");

        lsKDkamar.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lsKDkamarValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lsKDkamar);

        lsKDpenghuni.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lsKDpenghuniValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lsKDpenghuni);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(txtLama, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtNoReg, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTarif, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel7)
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(27, 27, 27)
                        .addComponent(txtNamaPenghuni, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNoReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(txtLama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtNamaPenghuni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 930, 140));

        tabelReg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelRegMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelReg);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 930, 170));

        btnSaveReg.setText("Save");
        btnSaveReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveRegActionPerformed(evt);
            }
        });

        btnUpdateReg.setText("Update");
        btnUpdateReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRegActionPerformed(evt);
            }
        });

        btnCancelReg.setText("Cancel");
        btnCancelReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelRegActionPerformed(evt);
            }
        });

        btnDeleteReg.setText("Delete");
        btnDeleteReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSaveReg, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelReg)
                .addGap(70, 70, 70))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveReg)
                    .addComponent(btnUpdateReg)
                    .addComponent(btnCancelReg)
                    .addComponent(btnDeleteReg))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 310, 50));
        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("TOTAL TARIF");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 160, -1));

        lblTotal.setBackground(new java.awt.Color(255, 248, 36));
        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText(" Rp. 0 ");
        lblTotal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblTotal.setOpaque(true);
        add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 400, 60));
    }// </editor-fold>//GEN-END:initComponents

    public void Validasi(){
        btnSaveReg.setEnabled(false);
        btnUpdateReg.setEnabled(false);
        btnDeleteReg.setEnabled(false);
    }
    
    private void lsKDkamarValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lsKDkamarValueChanged
        Object[] selectedItems = lsKDkamar.getSelectedValues();
        StringBuffer kdKamar = new StringBuffer();
        for (Object item : selectedItems) {
            kdKamar.append(item.toString());
        }
        
        try{
                Statement statement= (Statement) koneksi.GetConnection() .createStatement();
                ResultSet res=statement.executeQuery("select * from tb_kamar_826 where kode_kamar='"+ kdKamar +"';");
                while (res.next())
                {
                    String id_kamar = res.getString("kode_kamar");   
                    String Jenis = res.getString("jenis_kamar");
                    String Tarif = res.getString("tarif");
                             
                    txtJenis.setText(Jenis);
                    txtTarif.setText(Tarif);
                }

            }catch (Exception a){
                JOptionPane.showMessageDialog(null, "Data Kode Kamar Tidak Dapat Tampil!");
            }
        
        //Menghitung Total Tarif
        int Lama = Integer.parseInt(txtLama.getText());
        int Tarif = Integer.parseInt(txtTarif.getText());
        int totalTarif = Lama * Tarif;
        String total = String.valueOf(totalTarif);
        
        lblTotal.setText("Rp. " + total + " ");
        
    }//GEN-LAST:event_lsKDkamarValueChanged

    private void lsKDpenghuniValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lsKDpenghuniValueChanged
        
        if (txtLama.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Kolom Lama Menignap Tidak Boleh Kosong!");
        }else{
        Object[] selectedItems = lsKDpenghuni.getSelectedValues();
        StringBuffer kdPenghuni = new StringBuffer();
        for (Object item : selectedItems) {
            kdPenghuni.append(item.toString());
        }
        
        try{
                Statement statement= (Statement) koneksi.GetConnection() .createStatement();
                ResultSet res=statement.executeQuery("select * from tb_tamuhotel_826 where id_penghuni='"+ kdPenghuni +"';");
                while (res.next())
                {
                    String Nama = res.getString("nama_penghuni");   
                             
                    txtNamaPenghuni.setText(Nama);
                    
                }

            }catch (Exception a){
                JOptionPane.showMessageDialog(null, "Data Kode Kamar Tidak Dapat Tampil!");
            } 
        }
    }//GEN-LAST:event_lsKDpenghuniValueChanged

    public void datatableReg(){
    DefaultTableModel tbl=new DefaultTableModel();
        tbl.addColumn("No Reg");
        tbl.addColumn("Lama Menginap");
        tbl.addColumn("Tanggal Daftar");
        tbl.addColumn("Kode Kamar");
        tbl.addColumn("Tarif");
        tbl.addColumn("ID Penghuni");
        tbl.addColumn("Total Tarif");
        tabelReg.setModel(tbl);
//        tabelReg.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
//        tabelReg.getColumnModel().getColumn(0).setPreferredWidth(60);        
//        tabelReg.getColumnModel().getColumn(1).setPreferredWidth(200);
//        tabelReg.getColumnModel().getColumn(2).setPreferredWidth(80);                
        try{
            Statement statement= (Statement) koneksi.GetConnection() .createStatement();
            ResultSet res=statement.executeQuery("SELECT * FROM tb_registrasi_826");
                        
            while (res.next())
                
            {
                tbl.addRow(new Object[]{
//                    res.getString ("kode_kamar"),
//                    res.getString ("jenis_kamar"),
//                    res.getString ("tarif")
                    res.getString ("no_registrasi"),
                    res.getString ("lama_menginap"),
                    res.getString ("tanggal_daftar"),                        
                    res.getString ("kode_kamar"),                        
                    res.getString ("tarif"),
                    res.getString ("id_penghuni"),
                    res.getString ("total_tarif")
            });
                tabelReg.setModel(tbl);
        }
    }catch (Exception e){
        JOptionPane.showMessageDialog(tabelReg, "Data Registrasi Tidak Ditemukan");
        }
    }
    
    private void btnSaveRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveRegActionPerformed
        // TODO add your handling code here:
        
        SimpleDateFormat Date_Format = new SimpleDateFormat("dd-MM-yyyy");         
        if(txtNoReg.getText().equals("")){  
            JOptionPane.showMessageDialog(null,"ID Tidak Boleh Kosong"); 
            }else if (txtTarif.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Tarif Tidak Boleh Kosong"); 
            }else{
                String Id_Penghuni = lsKDpenghuni.getSelectedValue();
                String Kode_Kamar = lsKDkamar.getSelectedValue();
                String Lama = txtLama.getText();
                String No_Reg = txtNoReg.getText();
                String Tanggal = Date_Format.format(txtTanggal.getDate());
                String Tarif = txtTarif.getText();
                String Total = lblTotal.getText();
                try {
                    Statement statement = (Statement) koneksi.GetConnection() .createStatement();
                    statement.executeUpdate("insert into tb_registrasi_826 VALUES ('" 
                            + No_Reg + "','"+ Tanggal + "','"+ Lama + "',"
                            + "'"+ Tarif + "','"+ Total + "',"
                            + "'"+ Kode_Kamar + "','" + Id_Penghuni +"');");
                    statement.close();

                    JOptionPane.showMessageDialog(null, "Data Registrasi berhasil disimpan");
                }catch (Exception t){
                    JOptionPane.showMessageDialog(null, "Data Registrasi gagal disimpan");
                }
                datatableReg();
            }
        
    }//GEN-LAST:event_btnSaveRegActionPerformed

    private void btnCancelRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelRegActionPerformed
        // TODO add your handling code here:
        lsKDkamar.setSelectedIndex(0);
        lsKDpenghuni.setSelectedIndex(0);
        txtNoReg.setText("");
        txtJenis.setText("");
        txtTarif.setText("");
        txtNamaPenghuni.setText("");
        lblTotal.setText("Rp. 0 ");
    }//GEN-LAST:event_btnCancelRegActionPerformed

    private void btnDeleteRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRegActionPerformed
        // TODO add your handling code here:
        String noreg = txtNoReg.getText();
        
        try {
            Statement statement = (Statement) koneksi.GetConnection() .createStatement();
            statement.executeUpdate("DELETE from tb_registrasi_826 WHERE no_registrasi=('"+ noreg +"');");
            JOptionPane.showMessageDialog(null, "Berhasil Di Hapus");
            
            txtNoReg.setText("");
            txtNoReg.setText("");
            txtTarif.setText("");
            lblTotal.setText("Rp. 0");
            
        } catch (Exception t) {
            JOptionPane.showMessageDialog(null, "Gagal DI Hapus");
        }
        datatableReg();
        btnSaveReg.setEnabled(true);
        btnUpdateReg.setEnabled(true);
        btnDeleteReg.setEnabled(false);
    }//GEN-LAST:event_btnDeleteRegActionPerformed

    private void txtNoRegKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoRegKeyReleased
        // TODO add your handling code here:
        btnUpdateReg.setEnabled(false);
        btnDeleteReg.setEnabled(false);
        
        if(txtNoReg.getText().equals("")){
        btnSaveReg.setEnabled(false);        
        }else{
            btnSaveReg.setEnabled(true);
            
        }
    }//GEN-LAST:event_txtNoRegKeyReleased

    private void btnUpdateRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRegActionPerformed
        
        SimpleDateFormat Date_Format = new SimpleDateFormat("dd-MM-yyyy");   
        String Noreg  = txtNoReg.getText();
        String lama     = txtLama.getText();
        String Tanggal     = Date_Format.format(txtTanggal.getDate());
        String kode_kamar = lsKDkamar.getSelectedValue();
        String tarif = txtTarif.getText();
        String id_penghuni = lsKDpenghuni.getSelectedValue();
        String total = lblTotal.getText();
        
        try {
            PreparedStatement ps=(PreparedStatement) koneksi.GetConnection() .prepareStatement("UPDATE tb_registrasi_826 set " +
                    "lama_menginap=?, tanggal_daftar=?, kode_kamar=?, tarif=?, id_penghuni=?, total_tarif=? where no_registrasi=?");
            ps.setString(1, lama);
            ps.setString(2, Tanggal);
            ps.setString(3, kode_kamar);
            ps.setString(4, tarif);
            ps.setString(5, id_penghuni);
            ps.setString(6, total);
            ps.setString(7, Noreg);
            ps.executeUpdate();
            ps.close();
           JOptionPane.showMessageDialog(null, "Berhasil Diubah");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Diubah");
        }
        datatableReg();   
    }//GEN-LAST:event_btnUpdateRegActionPerformed

    private void tabelRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelRegMouseClicked
        // TODO add your handling code here:
        int kolom = 0;
        int baris = tabelReg.getSelectedRow();
        String Noreg        = tabelReg.getModel().getValueAt(baris, kolom).toString();
        String lama         = tabelReg.getModel().getValueAt(baris, 1).toString();
        String Tanggal      = tabelReg.getModel().getValueAt(baris, 2).toString();
        String kode_kamar   = tabelReg.getModel().getValueAt(baris, 3).toString();
        String tarif        = tabelReg.getModel().getValueAt(baris, 4).toString();
        String id_penghuni  = tabelReg.getModel().getValueAt(baris, 5).toString();
        String total        = tabelReg.getModel().getValueAt(baris, 6).toString();
        
        txtNoReg.setText(Noreg);
        txtLama.setText(lama);
        lsKDkamar.setSelectedValue(kode_kamar, true);
        txtTarif.setText(tarif);
        lsKDpenghuni.setSelectedValue(id_penghuni, true);
        lblTotal.setText(total);
        
        btnUpdateReg.setEnabled(true);
        btnDeleteReg.setEnabled(true);
        btnSaveReg.setEnabled(false);
    }//GEN-LAST:event_tabelRegMouseClicked

    public void comKDkamar(){
        
        DefaultListModel model = new DefaultListModel();
        
       try{
                Statement statement= (Statement) koneksi.GetConnection() .createStatement();
                ResultSet res=statement.executeQuery("select * from tb_kamar_826;");
                while (res.next())
                {
                    String id_penghuni = res.getString("kode_kamar");   
                    
                    model.addElement(id_penghuni);                    
                    lsKDkamar.setModel(model);
                }

            }catch (Exception a){
                JOptionPane.showMessageDialog(null, "Data Kode Kamar Tidak Dapat Tampil!");
            }
    }
    public void comKDpenghuni(){
        
        DefaultListModel model = new DefaultListModel();
        
       try{
                Statement statement= (Statement) koneksi.GetConnection() .createStatement();
                ResultSet res=statement.executeQuery("select * from tb_tamuhotel_826;");
                while (res.next())
                {
                    String id_kamar = res.getString("id_penghuni");   
                    
                    model.addElement(id_kamar);                    
                    lsKDpenghuni.setModel(model);
                }

            }catch (Exception a){
                JOptionPane.showMessageDialog(null, "Data Kode Kamar Tidak Dapat Tampil!");
            }
    }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelReg;
    private javax.swing.JButton btnDeleteReg;
    private javax.swing.JButton btnSaveReg;
    private javax.swing.JButton btnUpdateReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblTamu;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JList<String> lsKDkamar;
    private javax.swing.JList<String> lsKDpenghuni;
    private javax.swing.JTable tabelReg;
    private javax.swing.JTextField txtJenis;
    private javax.swing.JTextField txtLama;
    private javax.swing.JTextField txtNamaPenghuni;
    private javax.swing.JTextField txtNoReg;
    private com.toedter.calendar.JDateChooser txtTanggal;
    private javax.swing.JTextField txtTarif;
    // End of variables declaration//GEN-END:variables
}
