/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;
import com.mysql.jdbc.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author ADMIN-PC
 */
public class tamu
        extends javax.swing.JPanel {

    /**
     * Creates new form tamu
     */
    public tamu() {
        initComponents();
        datatableTamu();
        Validasi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReg1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTamu = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIDtamu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNamaTamu = new javax.swing.JTextField();
        btnSaveTamu = new javax.swing.JButton();
        btnDelTamu = new javax.swing.JButton();
        btnEdTamu = new javax.swing.JButton();
        btnCanTamu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReg1.setBackground(new java.awt.Color(204, 0, 0));
        lblReg1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblReg1.setForeground(new java.awt.Color(255, 255, 255));
        lblReg1.setText("                    TAMU");
        lblReg1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblReg1.setOpaque(true);
        lblReg1.setPreferredSize(new java.awt.Dimension(120, 23));
        add(lblReg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 11, 500, 32));

        tabelTamu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabelTamu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelTamu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTamuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelTamu);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 61, -1, 202));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 15, -1, -1));

        txtIDtamu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDtamuKeyReleased(evt);
            }
        });
        jPanel1.add(txtIDtamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 12, 81, -1));

        jLabel2.setText("NAMA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 53, -1, -1));
        jPanel1.add(txtNamaTamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 50, 133, -1));

        btnSaveTamu.setText("Save");
        btnSaveTamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveTamuActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveTamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 88, 67, -1));

        btnDelTamu.setText("Delete");
        btnDelTamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelTamuActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelTamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 88, 75, -1));

        btnEdTamu.setText("Update");
        btnEdTamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdTamuActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdTamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 117, -1, -1));

        btnCanTamu.setText("Cancel");
        btnCanTamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanTamuActionPerformed(evt);
            }
        });
        jPanel1.add(btnCanTamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 117, 75, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 61, 210, 200));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 750, 40));
    }// </editor-fold>//GEN-END:initComponents

    public void Validasi(){
        btnSaveTamu.setEnabled(false);
        btnEdTamu.setEnabled(false);
        btnDelTamu.setEnabled(false);
    }
    
    public void datatableTamu(){
        DefaultTableModel tbl=new DefaultTableModel();
        tbl.addColumn("ID");
        tbl.addColumn("Nama");
        tabelTamu.setModel(tbl);
        tabelTamu.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabelTamu.getColumnModel().getColumn(0).setPreferredWidth(60);        
        tabelTamu.getColumnModel().getColumn(1).setPreferredWidth(350);        
        try{
            Statement statement= (Statement) koneksi.GetConnection() .createStatement();
            ResultSet res=statement.executeQuery("SELECT * FROM tb_tamuhotel_826");
                        
            while (res.next())
                
            {
                tbl.addRow(new Object[]{
                    res.getString ("id_penghuni"),
                    res.getString ("nama_penghuni")
            });
                tabelTamu.setModel(tbl);
        }
    }catch (Exception e){
        JOptionPane.showMessageDialog(tabelTamu, "Data Tamu Tidak Ditemukan");
        }

    }
    
    private void btnSaveTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveTamuActionPerformed
        // TODO add your handling code here:
        if(txtIDtamu.getText().equals("")){  
            JOptionPane.showMessageDialog(null,"ID Tidak Boleh Kosong"); 
            }else if(txtNamaTamu.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Nama Tidak Boleh Kosong"); 
            }else{        
                String Id_Tamu = txtIDtamu.getText();
                String NamaTamu = txtNamaTamu.getText();
                try {
                    Statement statement = (Statement) koneksi.GetConnection() .createStatement();
                    statement.executeUpdate("insert into tb_tamuhotel_826 VALUES ('" + Id_Tamu + "','"+ NamaTamu +"');");
                    statement.close();

                    JOptionPane.showMessageDialog(null, "Data Tamu berhasil disimpan");
                }catch (Exception t){
                    JOptionPane.showMessageDialog(null, "Data Tamu gagal disimpan");
                }
                datatableTamu();
            }      
    }//GEN-LAST:event_btnSaveTamuActionPerformed

    private void btnEdTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdTamuActionPerformed
     
        String Id_Tamu  = txtIDtamu.getText();
        String Nama         = txtNamaTamu.getText();
        
        try {
            PreparedStatement ps=(PreparedStatement) koneksi.GetConnection() .prepareStatement("UPDATE tb_tamuhotel_826 set " +
                    "nama_penghuni=? where id_penghuni=?");
            ps.setString(1, Nama);
            ps.setString(2, Id_Tamu);
            ps.executeUpdate();
            ps.close();
           JOptionPane.showMessageDialog(null, "Berhasil Diubah");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Diubah");
        }
        datatableTamu();       
    }//GEN-LAST:event_btnEdTamuActionPerformed

    private void btnDelTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelTamuActionPerformed
        String Id_Tamu = txtIDtamu.getText();
        
        try {
            Statement statement = (Statement) koneksi.GetConnection() .createStatement();
            statement.executeUpdate("DELETE from tb_tamuhotel_826 WHERE id_penghuni=('"+Id_Tamu+"');");
            JOptionPane.showMessageDialog(null, "Berhasil Di Hapus");
            
            txtIDtamu.setText("");
            txtNamaTamu.setText("");
            
        } catch (Exception t) {
            JOptionPane.showMessageDialog(null, "Gagal DI Hapus");
        }
        datatableTamu();
        btnSaveTamu.setEnabled(true);
        btnEdTamu.setEnabled(true);
        btnDelTamu.setEnabled(false);
        
    }//GEN-LAST:event_btnDelTamuActionPerformed

    private void tabelTamuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTamuMouseClicked
        int kolom =0;
        int baris   = tabelTamu.getSelectedRow();
        String ID   = tabelTamu.getModel().getValueAt(baris, kolom).toString();
        String Nama = tabelTamu.getModel().getValueAt(baris, 1).toString();
        
        txtIDtamu.setText(ID);
        txtNamaTamu.setText(Nama);
        
        btnEdTamu.setEnabled(true);
        btnDelTamu.setEnabled(true);
        btnSaveTamu.setEnabled(false);
        
    }//GEN-LAST:event_tabelTamuMouseClicked

    private void btnCanTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanTamuActionPerformed
        txtIDtamu.setText("");
        txtNamaTamu.setText("");
    }//GEN-LAST:event_btnCanTamuActionPerformed

    private void txtIDtamuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDtamuKeyReleased
        if(txtIDtamu.getText().equals("")){
        btnSaveTamu.setEnabled(false);
        }else{
            btnSaveTamu.setEnabled(true);
            
        }
    }//GEN-LAST:event_txtIDtamuKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCanTamu;
    private javax.swing.JButton btnDelTamu;
    private javax.swing.JButton btnEdTamu;
    private javax.swing.JButton btnSaveTamu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblReg1;
    private javax.swing.JTable tabelTamu;
    private javax.swing.JTextField txtIDtamu;
    private javax.swing.JTextField txtNamaTamu;
    // End of variables declaration//GEN-END:variables
}
